spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventoappcloud
    username: root
    password: P@ssw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
