server:
  port: 8080

spring:
  application:
    name: eventoapp-apl01
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.port}
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
